version: '3.7'
services: 
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
    - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "vencejos"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456a"

  adminer:
    image: adminer
    container_name: adminer_mysql
    restart: always
    ports:
      - 8081:8080

    volumes: 
      - ./schemas:/var/lib/mysql:rw
volumes:
  schemas: {}


  
